//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public int GoodId { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }
        public int UsrId { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public int flag { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
