//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concern
    {
        public int ConId { get; set; }
        public System.DateTime time { get; set; }
        public int UsrA { get; set; }
        public int UsrB { get; set; }
    
        public virtual Usr Usr { get; set; }
        public virtual Usr Usr1 { get; set; }
    }
}
