//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pcomment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pcomment()
        {
            this.Preply = new HashSet<Preply>();
        }
    
        public int PcomId { get; set; }
        public string Content { get; set; }
        public System.DateTime time { get; set; }
        public string photo { get; set; }
        public string photodetail { get; set; }
        public int UsrId { get; set; }
        public int PhId { get; set; }
    
        public virtual Photograph Photograph { get; set; }
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preply> Preply { get; set; }
    }
}
