//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photograph
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photograph()
        {
            this.Pcomment = new HashSet<Pcomment>();
            this.Phpraise = new HashSet<Phpraise>();
        }
    
        public int PhId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string photo { get; set; }
        public string photodetail { get; set; }
        public System.DateTime time { get; set; }
        public string paishe { get; set; }
        public string chujing { get; set; }
        public string Brand { get; set; }
        public int UsrId { get; set; }
        public Nullable<int> ph_down { get; set; }
        public Nullable<int> ph_upvote { get; set; }
        public Nullable<int> ph_click { get; set; }
        public string ph_downId { get; set; }
        public string ph_upvoteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pcomment> Pcomment { get; set; }
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phpraise> Phpraise { get; set; }
    }
}
