//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relic
    {
        public int HFId { get; set; }
        public string name { get; set; }
        public string Himage { get; set; }
        public string describle { get; set; }
        public string zone { get; set; }
        public string Imagedetail { get; set; }
        public int RsortId { get; set; }
        public int RCategoryId { get; set; }
    
        public virtual RCategory RCategory { get; set; }
        public virtual Rsort Rsort { get; set; }
    }
}
