//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Vcomment = new HashSet<Vcomment>();
            this.Vpraise = new HashSet<Vpraise>();
        }
    
        public int VideoId { get; set; }
        public string Title { get; set; }
        public string Writing { get; set; }
        public string Content { get; set; }
        public int VsortId { get; set; }
        public int UsrId { get; set; }
        public Nullable<int> V_down { get; set; }
        public Nullable<int> V_upvote { get; set; }
        public Nullable<int> V_click { get; set; }
        public string V_downId { get; set; }
        public string V_upvoteId { get; set; }
    
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vcomment> Vcomment { get; set; }
        public virtual Vsort Vsort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vpraise> Vpraise { get; set; }
    }
}
