//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ShopCar
    {
        public int GoodId { get; set; }
        public string GName { get; set; }
        public string photo { get; set; }
        public double price { get; set; }
        public int CartId { get; set; }
        public int Count { get; set; }
        public string note { get; set; }
        public int flag { get; set; }
        public int UsrId { get; set; }
        public string UsrName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public double FinalPrice { get; set; }
    }
}
